spree-bitpay/config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  post '/payment_method/bit_payments/authenticate'
  get '/spree_bitpay/invoice/new', :to => "bitpay#pay_now", :as => :bitpay_pay_now
  get '/spree_bitpay/invoice/view', :to => "bitpay#view_invoice", :as => :bitpay_view_invoice
  get '/spree_bitpay/payment_sent', :to => "bitpay#payment_sent", :as => :bitpay_payment_sent
  get '/spree_bitpay/cancel', :to => "bitpay#cancel", :as => :bitpay_cancel
  get '/spree_bitpay/refresh', :to => "bitpay#refresh", :as => :bitpay_refresh
  get '/spree_bitpay/check', :to => "bitpay#check_payment_state", :as => :bitpay_check
  post '/spree_bitpay/notification', :to => "bitpay#notification", :as => :bitpay_notification
end

spree-bitpay/app/views/spree/admin/payments/source_views/_bitpayment.html.erb
<%  invoice = @payment.source.find_invoice  %>
<% if invoice %>
  <div class="bitpay_invoice_details">
    <h3>Bitpay Invoice Details</h3>
    <pre><%= JSON.pretty_generate(invoice) %></pre>
  </div>

  <%= link_to Spree.t(:bitpay_refresh_invoice), bitpay_refresh_url(payment: @payment), {id: "refresh_invoice", class: "button primary", title: Spree.t(:bitpay_refresh_invoice_description)} %>

  <div class="bitpay_invoice_details">
    <h3>Invoice</h3>
    <iframe id="bitpay_view_invoice_iframe"
            src="<%= j bitpay_view_invoice_url(source_id: @payment.source).html_safe %>"
            scrolling="no" 
            allowtransparency="true" 
            frameborder="0">
    </iframe>
    <br/>
    <%= link_to Spree.t(:bitpay_view_full_invoice), invoice["url"], {target: "_new"} %>
  </div>
<% else %>
  <p>No BitPay Invoice Available</p>
<% end %>