spree-bitpay/config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  post '/payment_method/bit_payments/authenticate'
  get '/spree_bitpay/invoice/new', :to => "bitpay#pay_now", :as => :bitpay_pay_now
  get '/spree_bitpay/invoice/view', :to => "bitpay#view_invoice", :as => :bitpay_view_invoice
  get '/spree_bitpay/payment_sent', :to => "bitpay#payment_sent", :as => :bitpay_payment_sent
  get '/spree_bitpay/cancel', :to => "bitpay#cancel", :as => :bitpay_cancel
  get '/spree_bitpay/refresh', :to => "bitpay#refresh", :as => :bitpay_refresh
  get '/spree_bitpay/check', :to => "bitpay#check_payment_state", :as => :bitpay_check
  post '/spree_bitpay/notification', :to => "bitpay#notification", :as => :bitpay_notification
end

spree-bitpay/app/views/spree/admin/shared/_bitpay_payment_preferences.html.erb
<% if @object.instance_of?(Spree::PaymentMethod::BitPayment) %>
  <% if @object.bit_pay_client and @object.paired? %>
    <div id="bitpay_pairing_status"><h4>Authenticated with <%= @object.api_uri %></h4></div>
    <div id="bitpay_help_text">This is the BitPay server that this payment method will use to create invoices and process payments.<br/>For more help, visit the <a href="https://github.com/bitpay/spree-bitpay">plugin homepage</a> or <a href="https://support.bitpay.com/hc/en-us/requests/new">submit a support request.</a></div>
  <% else %>

    <div id="bitpay_pairing_status"><h4>Not Authenticated</h4></div>
    <div id="bitpay_explanation_text">The TestNet option uses testnet bitcoin, which cannot be exchanged for bitcoin or for other currencies.<br/>For more help, visit the <a href="https://github.com/bitpay/spree-bitpay">plugin homepage</a> or <a href="https://support.bitpay.com/hc/en-us/requests/new">submit a support request.</a></div>
    <%= form_tag(payment_method_bit_payments_authenticate_path) do |f| %>
      <div class="form-group">
        <label>Connect to BitPay</label>
        <select class="select2" name="bitcoin_network" id="bitpay_api_uri">
          <option value="https://bitpay.com">LiveNet</option>
          <option value="https://test.bitpay.com">TestNet</option>
          <% if Rails.env == "development" || Rails.env == "test" %>
            <option value=<%= ENV['BPDEVSERVER'] %>>Development</option>
          <% end %>
        </select>
        <input type="hidden" name="redirect_url" value=<%= @_request.original_url %>>
        <input type="hidden" name="payment_method_id" value=<%= @payment_method.id %>>
        <input class="btn btn-primary" type="submit" value="Connect To BitPay">
      </div>
    <% end %>
  <% end %>
<% end %>